stages:
  - pre-check
  - codecheck
  - test
  - release


# WORKFLOW RULES
# ------------------------------------------------------------------------------------------------------
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH'
# ------------------------------------------------------------------------------------------------------


# TEMPLATES
# ------------------------------------------------------------------------------------------------------
.base_template:
  image: python:3.7-slim-buster
  tags:
    - build
    - internet

.idf_template:
  image: espressif/idf:latest
  tags:
    - build
    - internet
# --------------------------------------------------------------------------------------------------


# JOBS
# ------------------------------------------------------------------------------------------------------

include:
  - project: espressif/shared-ci-dangerjs
    ref: master
    file: danger.yaml
run-danger-mr-linter:
  stage: pre-check

# CODE CHECK BY PRE-COMMIT HOOKS
pre-commit_hooks_MR:
  stage: codecheck
  extends: .base_template
  before_script:
    - apt-get update && apt-get install -y -q git
    - python -m pip install pre-commit
  script:
    - echo "Merge request is from ${CI_COMMIT_REF_NAME} into ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} ${CI_COMMIT_REF_NAME}
    - export from_sha=$(git merge-base HEAD origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME})
    - echo "Checking changes from ${from_sha} to ${CI_COMMIT_SHA}:"
    - git log --oneline ${from_sha}..${CI_COMMIT_SHA}
    - echo "Modified files:"
    - git diff-tree --no-commit-id --name-only -r ${from_sha} ${CI_COMMIT_SHA}
    - echo "Running pre-commit:"
    - pre-commit run --from ${from_sha} --to ${CI_COMMIT_SHA}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Check if parse_soc_h_script got changed on IDF side
parse_soc_h_script_check:
  stage: codecheck
  extends: .idf_template
  script:
    - pip install .
    - python esp_coredump/corefile/_parse_soc_header.py
    - git diff --exit-code -- esp_coredump/corefile/soc_headers/\* || exit 1;
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

test_espcoredump:
  stage: test
  extends: .idf_template
  artifacts:
    when: on_failure
    paths:
      - "tests"
    expire_in: 1 week
  script:
    - pip install -e .
    - python esp_coredump/scripts/run_tests.py

# ------------------------------------------------------------------------------------------------------
